### ISSUE TITLE
Can't require package

### ISSUE THREAD

**Issue by gerob** [efficiently/authority-controller#19] opened 2015-03-16 20:16 UTC
```
composer require efficiently/authority-controller:2.0.*
```

and I get 

```
$ composer require efficiently/authority-controller:2.0.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package efficiently/authority-controller could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by tortuetorche** [comment] 2015-03-17 08:35
Hi @gerob,

It's an alpha release, so you need to tweak the `composer.json` file of your Laravel 5 application.
Add a `repositories` option:
```javascript
{
	//...
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/stayallive/authority"
		},
		{
			"type": "vcs",
			"url": "https://github.com/stayallive/authority-l5"
		}
	],
	//...
}
```
Then add these two options:
```javascript
{
	//...
	"prefer-stable": true,
	"minimum-stability": "dev"
}
```
Here a [composer.json sample](https://github.com/efficiently/laravel_authority-controller_app/blob/318d48ee42b8e63002d6d6a6cca34c868a63fb84/composer.json).

Duplicate of #18.

Cheers,
Tortue Torche

**Closed by tortuetorche** 2015-03-17 08:35 UTC
Labels: duplicate

**Comment by gerob** [comment] 2015-03-17 15:40
Thanks for the response Tortue. I ended up going with Entrust for L5 this time, I'll revisit this when it's out of alpha.

**Comment by tortuetorche** [comment] 2015-03-17 16:00
It's an alpha but it's pretty stable. When the next stable release of the [Authority](https://github.com/machuga/authority-l4) package will be out, I'll released a stable version.

My package is battle-tested, so it's safe to use it.
